import React from "react"
import { IconEdit } from "../ui/icons/IconEdit"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconEdit,
  "https://www.figma.com/design/e6Sjmed60NI77axindCYY3/Simple-Design-System---New?node-id=4039%3A11722",
  {
    props: {},
    example: (props) => <IconEdit />,
  },
)
